repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Format Rust source files
        language: system
        entry: cargo fmt --
        pass_filenames: false
      - id: Check Rust package
        name: Cargo check
        language: system
        entry: cargo check
        pass_filenames: false
      - id: cargo-clippy
        name: Run clippy linter
        language: system
        entry: cargo clippy --all-targets -- -Dwarnings
        pass_filenames: false
